---
version: '3'

includes:
  lint: .config/linter/Taskfile.yml
  npm: .config/npm/Taskfile.yml

tasks:
  code:
    cmds:
      - task: lint:megalinter

  build:
    cmds:
      - task: npm:install
      - task: npm:build

  deploy:
    cmds:
      - task: build
