---
version: '3'

tasks:
  megalinter:
    desc: MegaLinter is an Open-Source tool for CI/CD workflows
    ignore_error: true
    cmds:
      - cmd: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:rw -v $(pwd):/tmp/lint:rw oxsecurity/megalinter-javascript:v7
